language: java
sudo: false
jdk: oraclejdk8
install: mvn -Ptravis -DskipTests=true -Dmaven.javadoc.skip=true -B -V install
script:  mvn -Ptravis -Dmaven.javadoc.skip=true -q -B verify
cache:
  directories:
    - $HOME/.m2
git:
  depth: 10
env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "Mk2nLq4A9+EmweXDp8+VCXVCkjFXdITIWd/Rt3K2kCSNZFtRyxJ43CNvPlgapsDccZ4qNRfOco+/L2cPzZxAzi2I1CZ0JzFeEfTHPFlyXZS2//TqInGqOvngntVaJ+Up8BGCZUvQ8k8Mx2NrHp1AxolbchfMxUJXTf9KUEuK/4A="
addons:
  coverity_scan:
    project:
      name: "OryxProject/oryx"
      description: "Build submitted via Travis CI"
    notification_email: srowen@gmail.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile test-compile"
    branch_pattern: coverity_scan
